GITHUB_TOKEN = "PUT_YOUR_GITHUB_API_TOKEN_HERE"
APPVEYOR_TOKEN = "PUT_YOUR_APPVEYOR_API_TOKEN_HERE"
TRAVIS_TOKEN = "PUT_YOUR_TOKEN_API_TOKEN_HERE"
TRAVIS_GITHUB_TOKEN = "PUT_YOUR_TRAVIS_GITHUB_AUTH_TOKEN_HERE"